### ISSUE TITLE
jsdoc  documentation needs to be completed

### ISSUE THREAD

**Issue by ebabel-eu** [ebabel-eu/ebabel-utils#1]
**Describe the bug**
jsdoc is missing some description from functions.

**To Reproduce**
1. `npm run jsdoc`
2. browse to generated docs directory
3. check which functions have partial or no documentation

**Expected behavior**
All functions need to be documented via jsdoc.

**Comment by thalytafabrine** [comment]
can I do this?

**Comment by ebabel-eu** [comment]
Yes please! Let me know if you have any questions :) My email is hello@ebabel.eu
