### ISSUE TITLE
Refactor several modules into ebabel-utils

### ISSUE THREAD

**Issue by ebabel-eu** [ebabel-eu/ebabel-utils#3]
**Is your feature request related to a problem? Please describe.**
Several modules are too small to be a module in their own right.

**Describe the solution you'd like**
Refactor these modules into ebabel-utils.

**Additional context**
Modules to be refactored into ebabel-utils:

- ~~https://github.com/ebabel-games/ebabel-bounding-box~~
- https://github.com/ebabel-games/ebabel-count-array-elements
- https://github.com/ebabel-games/ebabel-distance
- https://github.com/ebabel-games/ebabel-guid
- https://github.com/ebabel-games/ebabel-ido
- https://github.com/ebabel-games/ebabel-prevent-xss
- https://github.com/ebabel-games/ebabel-random
- https://github.com/ebabel-games/ebabel-random-list

**Comment by dgapitts** [comment]
As agreed ebabel-bounding-box is now out of scope for ebabel-utils because it is not a pure function (dependency on THREE.js)

**Comment by dgapitts** [comment]
completed as per pull request: https://github.com/ebabel-games/ebabel-utils/pull/5
