### ISSUE TITLE
Add unit tests for new code

### ISSUE THREAD

**Issue by ebabel-eu** [ebabel-eu/ebabel-utils#7]
**Is your feature request related to a problem? Please describe.**
ebabel-utils test coverage used to be 100%. Now that new code has been added, it has fallen to less than 100% coverage.

**Describe the solution you'd like**
Add new unit tests to increase test coverage and make sure all new code is working correctly. Run `npm test` to see what code isn't 100% covered.

**Comment by dgapitts** [comment]
https://github.com/ebabel-games/ebabel-utils/pull/8#issue-220958813

**Comment by dgapitts** [comment]
test coverage for count-array-elements.js 89percent - one elusive branch
test coverage for random-list.test.js 95percent - one elusive branch
